spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scx_text?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: scxyasuo00
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        fromat_sql: true
server:
  port: 8181